# Generated by Django 6.0.4 on 2026-04-16 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_capital', models.DecimalField(decimal_places=2, max_digits=15)),
                ('start_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CalculationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('result_json', models.JSONField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='calculator.scenario')),
            ],
            options={
                'ordering': ['-calculated_at'],
            },
        ),
        migrations.CreateModel(
            name='InvestmentPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.PositiveIntegerField()),
                ('new_investment', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('growth_pct', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('new_growth_pct', models.DecimalField(decimal_places=5, default=0, max_digits=7)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periods', to='calculator.scenario')),
            ],
            options={
                'ordering': ['month'],
                'unique_together': {('scenario', 'month')},
            },
        ),
        migrations.CreateModel(
            name='InterestRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_months', models.PositiveIntegerField(choices=[(1, '1 Month'), (2, '2 Months'), (3, '3 Months'), (6, '6 Months'), (12, '1 Year'), (24, '2 Years'), (36, '3 Years'), (48, '4 Years'), (60, '5 Years'), (72, '6 Years'), (84, '7 Years'), (96, '8 Years'), (108, '9 Years'), (120, '10 Years'), (180, '15 Years')])),
                ('annual_rate', models.DecimalField(decimal_places=5, max_digits=7)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates', to='calculator.scenario')),
            ],
            options={
                'ordering': ['term_months'],
                'unique_together': {('scenario', 'term_months')},
            },
        ),
    ]
