# Generated by Django 6.0.4 on 2026-04-16 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloombergRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('rate_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_2m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_3m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_6m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_12m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_24m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_36m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_48m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_60m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_72m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_84m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_96m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_108m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_120m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_180m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='rate_mode',
            field=models.CharField(choices=[('bloomberg', 'Bloomberg Historical'), ('custom', 'Custom Rates'), ('forecast', 'Historical + Forecast')], default='bloomberg', max_length=20),
        ),
        migrations.CreateModel(
            name='ForecastRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('rate_1m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_2m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_3m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_6m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_12m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_24m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_36m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_48m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_60m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_72m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_84m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_96m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_108m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_120m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('rate_180m', models.DecimalField(blank=True, decimal_places=6, max_digits=10, null=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_rates', to='calculator.scenario')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('scenario', 'date')},
            },
        ),
    ]
